spring:
  application:
    name: task-service

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/zidio_task_management_sys
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8988

logging:
  level:
    org:
      springframework:
        security: DEBUG



